id: PFC2C8C5C
initial_creation_type: ocr
source_metadata:
  volumes:
    71c35b12c9084bcd90f9270ebb5bd503:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: མདོ་ཀུན་ལས་བཏུས་པའི་དོན་བསྡུས་པ།
      total_pages: 1902
      volume_number: 64
